# Generated by Django 2.0 on 2018-03-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Навчальний день',
                'verbose_name_plural': 'Навчальнні дні',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('group_weekend', models.BooleanField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клас',
                'verbose_name_plural': 'Створити розклад уроків для класу',
                'ordering': ('group_name',),
            },
        ),
        migrations.CreateModel(
            name='LessonName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(blank=True, default=None, max_length=124, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'ordering': ('lesson_name',),
            },
        ),
        migrations.CreateModel(
            name='LessonNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Номер уроку',
                'verbose_name_plural': 'Номери уроків',
                'ordering': ('lesson_number',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Номер Кабінета',
                'verbose_name_plural': 'Номери Кабінетів',
                'ordering': ('room_number',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, default=None, max_length=48, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Вчитель',
                'verbose_name_plural': 'Вчителі',
                'ordering': ('teacher_name',),
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(blank=True, default=None, null=True, on_delete=False, to='ControlPanel1.Day')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=False, to='ControlPanel1.Group')),
                ('lesson_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=False, to='ControlPanel1.LessonName')),
                ('lesson_number', models.ForeignKey(blank=True, default=None, null=True, on_delete=False, to='ControlPanel1.LessonNumber')),
                ('room_number', models.ForeignKey(blank=True, default=None, null=True, on_delete=False, to='ControlPanel1.Room')),
                ('teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=False, to='ControlPanel1.Teacher')),
            ],
            options={
                'verbose_name': 'Розклад уроків',
                'verbose_name_plural': 'Розклад уроків',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_name', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Навчальний тиждень',
                'verbose_name_plural': 'Навчальні тижні',
            },
        ),
        migrations.AddField(
            model_name='timetable',
            name='week',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=False, to='ControlPanel1.Week'),
        ),
    ]
